# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: crazycuc|以学愈愚
email: crazycuc@163.com
description: > # this means to ignore newlines until "baseurl:"
  刘向《说苑·建本》：“夫幼者必愚，愚者妄行。愚者妄行，不能保身。 孟子 曰：‘人皆知以食愈饥，莫知以学愈愚。’故善材之幼者，必勤於学问，以修其性。”
  
  ICP主体备案号   粤ICP备17113698号
baseurl: "" # the subpath of your site, e.g. /blog
url: "www.crazycuc.github.io" # the base hostname & protocol for your site, e.g. http://example.com
 
ICP主体备案号   粤ICP备17113698号
github_username:  crazycuc

# Build settings
markdown: kramdown
theme: jekyll-theme-tactile
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
